### ISSUE TITLE
Error: Cannot find library D in loadpath

### ISSUE THREAD

**Issue by k32l** [snu-sf-class/pl2016#8]
I try to compile in coqIDE, it gives me an error "Cannot find library D in loadpath". However if I erase line "Require Export D" it works well. Do I need to upload any libraries?

**Comment by jeehoonkang** [comment]
It's my mistake; sorry.  I will upload the new version.

**Comment by jeehoonkang** [comment]
Thank you for the report.  Hope the bug is fixed in https://github.com/snu-sf-class/pl2016/commit/3d629451eabe984fcacdc5c82ae6c27d1ac3d8a0

**Comment by jeehoonkang** [comment]
Please let me know whether your problem is solved, so that I can close this issue.

**Comment by isutare412** [comment]
There still comes a same error. Even i pulled the repository. I still cannot pass the "Require Export D." line.

**Comment by jeehoonkang** [comment]
Did you `make` before running it in the ide?

**Comment by isutare412** [comment]
No... actually I cannot 

> make

 because of an error.

**Comment by isutare412** [comment]
No... actually i cannot **make** because of an error.

**Comment by jeehoonkang** [comment]
@isutare412 guess you did not install coq, or path is not set.  Make sure coq_makefile is in the path variable.

**Comment by isutare412** [comment]
/Applications/CoqIDE_8.4pl5.app/Contents/Resources/bin/coq_makefile
I checked coq_makefile in the bin directory.

I also added environment path in my .bash_profile
`export COQBIN=/Applications/CoqIDE_8.4pl5.app/Contents/Resources/bin/`
`export COQLIB=/Applications/CoqIDE_8.4pl5.app/Contents/Resources/bin/`
`export COQTOP=/Applications/CoqIDE_8.4pl5.app/Contents/Resources/bin/coqtop`

I still don't know whats the problem....

**Comment by jeehoonkang** [comment]
Related: #10

**Comment by jeehoonkang** [comment]
Duplicate #15
